framework:
    secret: '\kSZ6Jkd>t)Tb<KKf~<5FF*ML(VAFhFq'
    templating:
        engines: ['twig']
    profiler: { only_exceptions: false }
    default_locale: '%default_locale%'
    translator:
        fallbacks: ['%default_locale%']

twig:
    paths: ['%kernel.project_dir%/templates']
    globals:
        app_title: 'App Title'
        app_description: 'App Description'
        app_url: 'http://www.example.de'
        app_keywords: 'One,Two,Three'

swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    port:      "%mailer_port%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    encryption: "%mailer_encryption%"
