framework:
    secret: S0ME_SECRET
    templating:
        engines: ['twig']
    profiler: { only_exceptions: false }

twig:
    paths: ['%kernel.project_dir%/templates']
    globals:
        app_title: 'App Title'
        app_description: 'App Description'
        app_url: 'http://www.example.de'
        app_keywords: 'One,Two,Three'
